# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/balance/work/FPGA/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_bram_if_cntlr_0/urbana_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'urbana_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/balance/work/FPGA/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_bram_if_cntlr_0/urbana_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urbana_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/balance/work/FPGA/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_bram_if_cntlr_0/urbana_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'urbana_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/balance/work/FPGA/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_bram_if_cntlr_0/urbana_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urbana_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
