# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/urbana.xdc

# Block Designs: bd/urbana/urbana.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana || ORIG_REF_NAME==urbana} -quiet] -quiet

# IP: bd/urbana/ip/urbana_microblaze_0_0/urbana_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_microblaze_0_0 || ORIG_REF_NAME==urbana_microblaze_0_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_axi_uartlite_0_0/urbana_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_axi_uartlite_0_0 || ORIG_REF_NAME==urbana_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_mdm_1_1/urbana_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_mdm_1_1 || ORIG_REF_NAME==urbana_mdm_1_1} -quiet] -quiet

# IP: bd/urbana/ip/urbana_clk_wiz_1_1/urbana_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_clk_wiz_1_1 || ORIG_REF_NAME==urbana_clk_wiz_1_1} -quiet] -quiet

# IP: bd/urbana/ip/urbana_rst_clk_wiz_1_100M_0/urbana_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==urbana_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_axi_interconnect_0_1/urbana_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_axi_interconnect_0_1 || ORIG_REF_NAME==urbana_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/urbana/ip/urbana_xbar_1/urbana_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_xbar_1 || ORIG_REF_NAME==urbana_xbar_1} -quiet] -quiet

# IP: bd/urbana/ip/urbana_dlmb_v10_0/urbana_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_dlmb_v10_0 || ORIG_REF_NAME==urbana_dlmb_v10_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_ilmb_v10_0/urbana_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_ilmb_v10_0 || ORIG_REF_NAME==urbana_ilmb_v10_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_dlmb_bram_if_cntlr_0/urbana_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==urbana_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_ilmb_bram_if_cntlr_0/urbana_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==urbana_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_lmb_bram_0/urbana_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_lmb_bram_0 || ORIG_REF_NAME==urbana_lmb_bram_0} -quiet] -quiet

# IP: bd/urbana/ip/urbana_aes_0_1/urbana_aes_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urbana_aes_0_1 || ORIG_REF_NAME==urbana_aes_0_1} -quiet] -quiet

# XDC: bd/urbana/urbana_ooc.xdc
