# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7s50csga324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.cache/wt [current_project]
set_property parent.project_path D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/Security/nthu_fpga_system/axi_ip
  d:/Security/HW4
  d:/Security/nthu_ip_location
} [current_project]
set_property ip_output_repo d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/hdl/urbana_wrapper.v
add_files D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/urbana.bd
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_microblaze_0_0/urbana_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_microblaze_0_0/urbana_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_microblaze_0_0/urbana_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_axi_uartlite_0_0/urbana_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_axi_uartlite_0_0/urbana_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_axi_uartlite_0_0/urbana_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_mdm_1_1/urbana_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_mdm_1_1/urbana_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_clk_wiz_1_1/urbana_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_clk_wiz_1_1/urbana_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_clk_wiz_1_1/urbana_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_rst_clk_wiz_1_100M_0/urbana_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_rst_clk_wiz_1_100M_0/urbana_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_rst_clk_wiz_1_100M_0/urbana_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_xbar_1/urbana_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_dlmb_v10_0/urbana_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_dlmb_v10_0/urbana_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_v10_0/urbana_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_v10_0/urbana_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_dlmb_bram_if_cntlr_0/urbana_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_ilmb_bram_if_cntlr_0/urbana_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/ip/urbana_lmb_bram_0/urbana_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/sources_1/bd/urbana/urbana_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/constrs_1/new/urbana.xdc
set_property used_in_implementation false [get_files D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/constrs_1/new/urbana.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top urbana_wrapper -part xc7s50csga324-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef urbana_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file urbana_wrapper_utilization_synth.rpt -pb urbana_wrapper_utilization_synth.pb"
