set_property SRC_FILE_INFO {cfile:D:/Security/nthu_sys_lcm_only/nthu_sys_lcm_only.srcs/constrs_1/new/urbana.xdc rfile:../../../nthu_sys_lcm_only.srcs/constrs_1/new/urbana.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports clk_in1_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports resetn_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
